[package]
name = "mem-client"
version = "0.1.0"
edition = "2021"

[dependencies]
memex-core = { path = "../core" }
anyhow.workspace = true
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
